# Generated by Django 5.0.3 on 2024-04-01 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegrampost',
            name='message_id',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
    ]
