# Generated by Django 5.0.3 on 2024-04-02 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0002_telegrampost_message_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegrampost',
            name='channel_name',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
