# Generated by Django 5.0.3 on 2024-03-31 21:36

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workspace', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('text', models.TextField(max_length=4096)),
                ('photos', django.contrib.postgres.fields.ArrayField(base_field=models.FilePathField(), size=None)),
                ('files', django.contrib.postgres.fields.ArrayField(base_field=models.FilePathField(), size=None)),
                ('send_planned_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('PENDING', 'Pending Publication'), ('UNDER_REVIEW', 'Under Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='CREATED', max_length=20)),
                ('number_of_people', models.IntegerField()),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_posts', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workspace.workspace')),
            ],
        ),
    ]
