# Generated by Django 4.2.11 on 2024-04-02 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='channel_username',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='channelrequest',
            name='channel_username',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
