# Generated by Django 5.0.3 on 2024-03-31 20:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0002_channelrequest'),
        ('workspace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='workspace',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='workspace.workspace'),
            preserve_default=False,
        ),
    ]
