# Generated by Django 5.0.3 on 2024-04-02 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='chat_id',
            field=models.BigIntegerField(),
        ),
    ]
