# Generated by Django 5.0.3 on 2024-04-01 17:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('telegram_id', models.BigIntegerField(unique=True)),
                ('telegram_username', models.CharField(max_length=32)),
                ('avatar', models.FileField(default=None, null=True, upload_to='user/avatars/')),
                ('last_logged_in', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
