# Generated by Django 5.0.3 on 2024-04-01 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='avatar_path',
        ),
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.FileField(default=None, null=True, upload_to='user/avatars/'),
        ),
    ]
